<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:property name="arm_length" value="0.1" />
    <xacro:property name="arm_width" value="0.1" />
    <xacro:property name="arm_height" value="0.02" />
    <xacro:property name="arm_mass" value="0.5" />


    <xacro:property name="forearm_mass" value="0.3" />
    <xacro:property name="forearm_length" value="0.3" />
    <xacro:property name="forearm_radius" value="0.02" />


    <xacro:property name="hand_mass" value="0.3" />
    <xacro:property name="hand_length" value="0.3" />
    <xacro:property name="hand_radius" value="0.02" />


    <!-- <link name="base_footprint">
    </link> -->
    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_length} ${arm_width} ${arm_height}" />
            </geometry>
            <material name="orange" />
            <origin xyz="0 0 ${arm_height / 2.0}" rpy="0 0 0" />
        </visual>
        <collision>
            <geometry>
                <box size="${arm_length} ${arm_width} ${arm_height}" />
            </geometry>
            <origin xyz="0 0 ${arm_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="${arm_mass}" l="${2*arm_length}" w="${2*arm_width}" h="${2*arm_height}"
            xyz="0 0 ${arm_height / 2.0}" rpy="0 0 0" />
    </link>

    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder length="${forearm_length}" radius="${forearm_radius}" />
            </geometry>
            <material name="yellow" />
            <origin xyz="0 0 ${forearm_length / 2.0}" rpy="0 0 0" />
        </visual>
        <collision>
            <geometry>
                <cylinder length="${forearm_length}" radius="${forearm_radius}" />
            </geometry>
            <origin xyz="0 0 ${forearm_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="${forearm_mass}" r="${2*forearm_radius}" h="${2*forearm_length}"
            xyz="0 0 ${forearm_length / 2.0}" rpy="0 0 0" />
    </link>

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder length="${hand_length}" radius="${hand_radius}" />
            </geometry>
            <material name="orange" />
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
        </visual>
        <collision>
            <geometry>
                <cylinder length="${hand_length}" radius="${hand_radius}" />
            </geometry>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="${hand_mass}" r="${2*hand_radius}" h="${2*hand_length}"
            xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />

    </link>
    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link" />
        <child link="hand_link" />
        <axis xyz="0 1 0" />
        <limit effort="100.0" lower="0.0" upper="${pi / 2}" velocity="100.0" />
        <dynamics friction="0.05" damping="0.1" />
        <origin xyz="0 0 ${forearm_length}" rpy="0 0 0" />
    </joint>


    <!-- <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="arm_base_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint> -->

    <joint name="arm_base_forearm_joint" type="revolute">
        <parent link="arm_base_link" />
        <child link="forearm_link" />
        <axis xyz="0 1 0" />
        <limit effort="100.0" lower="0.0" upper="${pi / 2}" velocity="100.0" />
        <dynamics friction="0.05" damping="0.1" />
        <origin xyz="0 0 ${arm_height / 2}" rpy="0 0 0" />
    </joint>



    <gazebo>
        <plugin name="gazebo_ros_joint_pose_trajectory"
            filename="libgazebo_ros_joint_pose_trajectory.so">
            <!-- Update rate in Hz -->
            <update_rate>2</update_rate>
        </plugin>

    </gazebo>

    <gazebo>
        <plugin name="gazebo_ros_joint_state_publisher"
            filename="libgazebo_ros_joint_state_publisher.so">

            <!-- Update rate in Hertz -->
            <update_rate>10</update_rate>

            <!-- Name of joints in the model whose states will be published. -->
            <joint_name>arm_base_forearm_joint</joint_name>
            <joint_name>forearm_hand_joint</joint_name>

        </plugin>
    </gazebo>
    <gazebo reference="base_link">
        <material> Gazebo/Blue </material>
    </gazebo>
    <gazebo reference="hand_link">
        <material> Gazebo/Orange</material>
    </gazebo>
    <gazebo reference="forearm_link">
        <material> Gazebo/Yellow</material>
    </gazebo>
    <gazebo reference="arm_base_link">
        <material> Gazebo/Orange</material>
    </gazebo>

</robot>